In [1]:
import pandas as pd
import glob

In [2]:
csv_files = glob.glob("Movies/*.csv")

dfs = []
for file in csv_files:
    df = pd.read_csv(file)
    dfs.append(df)
all_movies = pd.concat(dfs)
movies = all_movies.drop_duplicates(subset=['movie_name'], keep='first')
movies.to_csv('combined_movies.csv', index=False)

In [3]:
movies1 = pd.read_csv("combined_movies.csv")

In [4]:
movies1.head(50)

,movie_id,movie_name,year,certificate,runtime,genre,rating,description,director,director_id,star,star_id,votes,gross(in $)
0,tt9114286,Black Panther: Wakanda Forever,2022,PG-13,161 min,"Action, Adventure, Drama",6.9,The people of Wakanda fight to protect their h...,Ryan Coogler,/name/nm3363032/,"Letitia Wright, \nLupita Nyong'o, \nDanai Guri...","/name/nm4004793/,/name/nm2143282/,/name/nm1775...",204835.0,NaN
1,tt1630029,Avatar: The Way of Water,2022,PG-13,192 min,"Action, Adventure, Fantasy",7.8,Jake Sully lives with his newfound family form...,James Cameron,/name/nm0000116/,"Sam Worthington, \nZoe Saldana, \nSigourney We...","/name/nm0941777/,/name/nm0757855/,/name/nm0000...",295119.0,NaN
2,tt5884796,Plane,2023,R,107 min,"Action, Thriller",6.5,A pilot finds himself caught in a war zone aft...,Jean-François Richet,/name/nm0724938/,"Gerard Butler, \nMike Colter, \nTony Goldwyn, ...","/name/nm0124930/,/name/nm1591496/,/name/nm0001...",26220.0,NaN
3,tt6710474,Everything Everywhere All at Once,2022,R,139 min,"Action, Adventure, Comedy",8.0,A middle-aged Chinese immigrant is swept up in...,"Dan Kwan, \nDaniel Scheinert",/name/nm3453283/,"Michelle Yeoh, \nStephanie Hsu, \nJamie Lee Cu...","/name/nm3215397/,/name/nm0000706/,/name/nm3513...",327858.0,NaN
4,tt5433140,Fast X,2023,NaN,NaN,"Action, Crime, Mystery",NaN,Dom Toretto and his family are targeted by the...,Louis Leterrier,/name/nm0504642/,"Vin Diesel, \nJordana Brewster, \nTyrese Gibso...","/name/nm0004874/,/name/nm0108287/,/name/nm0879...",NaN,NaN
5,tt10954600,Ant-Man and the Wasp: Quantumania,2023,PG-13,125 min,"Action, Adventure, Comedy",6.6,"Scott Lang and Hope Van Dyne, along with Hank ...",Peyton Reed,/name/nm0715636/,"Paul Rudd, \nEvangeline Lilly, \nJonathan Majo...","/name/nm0748620/,/name/nm1431940/,/name/nm3718...",5396.0,NaN
6,tt9686790,Shotgun Wedding,2022,R,100 min,"Action, Comedy, Romance",5.4,Darcy and Tom gather their families for the ul...,Jason Moore,/name/nm0601337/,"Jennifer Lopez, \nJosh Duhamel, \nLenny Kravit...","/name/nm0000182/,/name/nm0241049/,/name/nm0005...",21529.0,NaN
7,tt12593682,Bullet Train,2022,R,127 min,"Action, Comedy, Thriller",7.3,Five assassins aboard a swiftly-moving bullet ...,David Leitch,/name/nm0500610/,"Brad Pitt, \nJoey King, \nAaron Taylor-Johnson...","/name/nm0000093/,/name/nm1428821/,/name/nm1093...",293635.0,NaN
8,tt1016150,All Quiet on the Western Front,2022,R,148 min,"Action, Drama, War",7.8,A young German soldier's terrifying experience...,Edward Berger,/name/nm0074163/,"Felix Kammerer, \nAlbrecht Schuch, \nAaron Hil...","/name/nm0436835/,/name/nm3477129/,/name/nm6037...",139754.0,NaN
9,tt1745960,Top Gun: Maverick,2022,PG-13,130 min,"Action, Drama",8.3,"After thirty years, Maverick is still pushing ...",Joseph Kosinski,/name/nm2676052/,"Tom Cruise, \nJennifer Connelly, \nMiles Telle...","/name/nm0000129/,/name/nm0000124/,/name/nm1886...",526016.0,NaN
10,tt12844910,Pathaan,2023,Not Rated,146 min,"Action, Adventure, Drama",6.6,An Indian spy takes on the leader of a group o...,Siddharth Anand,/name/nm1893457/,"Shah Rukh Khan, \nDeepika Padukone, \nJohn Abr...","/name/nm0451321/,/name/nm2138653/,/name/nm1303...",120080.0,NaN
11,tt15486810,Teen Wolf: The Movie,2023,TV-MA,140 min,"Action, Drama, Fantasy",5.6,A terrifying evil has emerged. The wolves howl...,Russell Mulcahy,/name/nm0611683/,"Tyler Posey, \nCrystal Reed, \nHolland Roden, ...","/name/nm0692677/,/name/nm3706952/,/name/nm1555...",9026.0,NaN
12,tt1825683,Black Panther,2018,PG-13,134 min,"Action, Adventure, Sci-Fi",7.3,"T'Challa, heir to the hidden but advanced king...",Ryan Coogler,/name/nm3363032/,"Chadwick Boseman, \nMichael B. Jordan, \nLupit...","/name/nm1569276/,/name/nm0430107/,/name/nm2143...",785813.0,700059566.0
13,tt1877830,The Batman,2022,PG-13,176 min,"Action, Crime, Drama",7.8,When a sadistic serial killer begins murdering...,Matt Reeves,/name/nm0716257/,"Robert Pattinson, \nZoë Kravitz, \nJeffrey Wri...","/name/nm1500155/,/name/nm2368789/,/name/nm0942...",672146.0,NaN
14,tt0092099,Top Gun,1986,PG,109 min,"Action, Drama",6.9,As students at the United States Navy's elite ...,Tony Scott,/name/nm0001716/,"Tom Cruise, \nTim Robbins, \nKelly McGillis, \...","/name/nm0000129/,/name/nm0000209/,/name/nm0000...",461419.0,179800601.0
15,tt0499549,Avatar,2009,PG-13,162 min,"Action, Adventure, Fantasy",7.9,A paraplegic Marine dispatched to the moon Pan...,James Cameron,/name/nm0000116/,"Sam Worthington, \nZoe Saldana, \nSigourney We...","/name/nm0941777/,/name/nm0757855/,/name/nm0000...",1322694.0,760507625.0
16,tt13539646,The Wandering Earth II,2023,NaN,173 min,"Action, Adventure, Drama",8.0,Humans built huge engines on the surface of th...,Frant Gwo,/name/nm4914792/,"Andy Lau, \nZina Blahusova, \nJing Wu, \nClara...","/name/nm0490489/,/name/nm1927842/,/name/nm0943...",7081.0,NaN
17,tt6443346,Black Adam,2022,PG-13,125 min,"Action, Adventure, Fantasy",6.4,"Nearly 5,000 years after he was bestowed with ...",Jaume Collet-Serra,/name/nm1429471/,"Dwayne Johnson, \nAldis Hodge, \nPierce Brosna...","/name/nm0425005/,/name/nm0388038/,/name/nm0000...",222934.0,NaN
18,tt7985704,Operation Fortune: Ruse de guerre,2023,R,114 min,"Action, Comedy, Thriller",6.7,Special agent Orson Fortune and his team of op...,Guy Ritchie,/name/nm0005363/,"Jason Statham, \nAubrey Plaza, \nCary Elwes, \...","/name/nm0005458/,/name/nm2201555/,/name/nm0000...",10785.0,NaN
19,tt8041270,Jurassic World: Dominion,2022,PG-13,147 min,"Action, Adventure, Sci-Fi",5.6,Four years after the destruction of Isla Nubla...,Colin Trevorrow,/name/nm1119880/,"Chris Pratt, \nBryce Dallas Howard, \nLaura De...","/name/nm0695435/,/name/nm0397171/,/name/nm0000...",171780.0,NaN
20,tt1392170,The Hunger Games,2012,PG-13,142 min,"Action, Adventure, Sci-Fi",7.2,Katniss Everdeen voluntarily takes her younger...,Gary Ross,/name/nm0002657/,"Jennifer Lawrence, \nJosh Hutcherson, \nLiam H...","/name/nm2225369/,/name/nm1242688/,/name/nm2955...",927499.0,408010692.0
21,tt7693316,Devotion,2022,PG-13,139 min,"Action, Drama, War",6.6,A pair of U.S. Navy fighter pilots risk their ...,J.D. Dillard,/name/nm2300570/,"Jonathan Majors, \nGlen Powell, \nChristina Ja...","/name/nm3718007/,/name/nm1412974/,/name/nm2325...",15135.0,NaN
22,tt11138512,The Northman,2022,R,137 min,"Action, Adventure, Drama",7.1,A young Viking prince is on a quest to avenge ...,Robert Eggers,/name/nm3211470/,"Alexander Skarsgård, \nNicole Kidman, \nClaes ...","/name/nm0002907/,/name/nm0000173/,/name/nm0051...",217036.0,NaN
23,tt1160419,Dune,2021,PG-13,155 min,"Action, Adventure, Drama",8.0,A noble family becomes embroiled in a war for ...,Denis Villeneuve,/name/nm0898288/,"Timothée Chalamet, \nRebecca Ferguson, \nZenda...","/name/nm3154303/,/name/nm0272581/,/name/nm3918...",649342.0,108327830.0
24,tt0439572,The Flash,2023,NaN,NaN,"Action, Adventure, Fantasy",NaN,Barry Allen uses his super speed to change the...,Andy Muschietti,/name/nm0615592/,"Ben Affleck, \nMichael Shannon, \nMichael Keat...","/name/nm0000255/,/name/nm0788335/,/name/nm0000...",NaN,NaN
25,tt11291274,The Unbearable Weight of Massive Talent,2022,R,107 min,"Action, Comedy, Crime",7.0,"In this action-packed comedy, Nicolas Cage pla...",Tom Gormican,/name/nm3230448/,"Nicolas Cage, \nPedro Pascal, \nTiffany Haddis...","/name/nm0000115/,/name/nm0050959/,/name/nm1840...",97887.0,NaN
26,tt8093700,The Woman King,2022,PG-13,135 min,"Action, Drama, History",6.7,A historical epic inspired by true events that...,Gina Prince-Bythewood,/name/nm0697656/,"Viola Davis, \nThuso Mbedu, \nLashana Lynch, \...","/name/nm0205626/,/name/nm9096847/,/name/nm2736...",48483.0,NaN
27,tt8178634,RRR,2022,Not Rated,187 min,"Action, Adventure, Drama",7.9,A fictitious story about two legendary revolut...,S.S. Rajamouli,/name/nm1442514/,"N.T. Rama Rao Jr., \nRam Charan Teja, \nAjay D...","/name/nm1694524/,/name/nm2776304/,/name/nm0222...",135454.0,NaN
28,tt0120737,The Lord of the Rings: The Fellowship of the Ring,2001,PG-13,178 min,"Action, Adventure, Drama",8.8,A meek Hobbit from the Shire and eight compani...,Peter Jackson,/name/nm0001392/,"Elijah Wood, \nIan McKellen, \nOrlando Bloom, ...","/name/nm0000704/,/name/nm0005212/,/name/nm0089...",1889727.0,315544750.0
29,tt4873118,The Covenant,2023,R,NaN,"Action, Crime, Thriller",NaN,"Follows Sergeant John, who on his last tour of...",Guy Ritchie,/name/nm0005363/,"Jake Gyllenhaal, \nAlexander Ludwig, \nAntony ...","/name/nm0350453/,/name/nm1573253/,/name/nm1102...",NaN,NaN
30,tt10648342,Thor: Love and Thunder,2022,PG-13,118 min,"Action, Adventure, Comedy",6.3,"Thor enlists the help of Valkyrie, Korg and ex...",Taika Waititi,/name/nm0169806/,"Chris Hemsworth, \nNatalie Portman, \nChristia...","/name/nm1165110/,/name/nm0000204/,/name/nm0000...",344327.0,NaN
31,tt2906216,Dungeons & Dragons: Honor Among Thieves,2023,NaN,134 min,"Action, Adventure, Fantasy",NaN,A charming thief and a band of unlikely advent...,"John Francis Daley, \nJonathan Goldstein",/name/nm0197855/,"Chris Pine, \nMichelle Rodriguez, \nRegé-Jean ...","/name/nm0326246/,/name/nm1517976/,/name/nm0735...",NaN,NaN
32,tt15829724,The Locksmith,2023,NaN,92 min,"Action, Mystery, Thriller",4.6,"A thief fresh out of prison, tries to work his...",Nicolas Harvard,/name/nm1189187/,"Kate Bosworth, \nRyan Phillippe, \nJeffrey Nor...","/name/nm0098378/,/name/nm0000202/,/name/nm0635...",577.0,NaN
33,tt0468569,The Dark Knight,2008,PG-13,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,/name/nm0634240/,"Christian Bale, \nHeath Ledger, \nAaron Eckhar...","/name/nm0000288/,/name/nm0005132/,/name/nm0001...",2675531.0,534858444.0
34,tt1375666,Inception,2010,PG-13,148 min,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,Christopher Nolan,/name/nm0634240/,"Leonardo DiCaprio, \nJoseph Gordon-Levitt, \nE...","/name/nm0000138/,/name/nm0330687/,/name/nm0680...",2373682.0,292576195.0
35,tt10872600,Spider-Man: No Way Home,2021,PG-13,148 min,"Action, Adventure, Fantasy",8.2,"With Spider-Man's identity now revealed, Peter...",Jon Watts,/name/nm1218281/,"Tom Holland, \nZendaya, \nBenedict Cumberbatch...","/name/nm4043618/,/name/nm3918035/,/name/nm1212...",770492.0,804747988.0
36,tt1462764,Indiana Jones and the Dial of Destiny,2023,NaN,NaN,"Action, Adventure",NaN,The plot is unknown at this time.,James Mangold,/name/nm0003506/,"Harrison Ford, \nMads Mikkelsen, \nBoyd Holbro...","/name/nm0000148/,/name/nm0586568/,/name/nm2933...",NaN,NaN
37,tt10366206,John Wick: Chapter 4,2023,NaN,169 min,"Action, Crime, Thriller",NaN,John Wick uncovers a path to defeating The Hig...,Chad Stahelski,/name/nm0821432/,"Keanu Reeves, \nDonnie Yen, \nBill Skarsgård, ...","/name/nm0000206/,/name/nm0947447/,/name/nm0803...",NaN,NaN
38,tt0172495,Gladiator,2000,R,155 min,"Action, Adventure, Drama",8.5,A former Roman General sets out to exact venge...,Ridley Scott,/name/nm0000631/,"Russell Crowe, \nJoaquin Phoenix, \nConnie Nie...","/name/nm0000128/,/name/nm0001618/,/name/nm0001...",1512747.0,187705427.0
39,tt4154796,Avengers: Endgame,2019,PG-13,181 min,"Action, Adventure, Drama",8.4,After the devastating events of Avengers: Infi...,"Anthony Russo, \nJoe Russo",/name/nm0751577/,"Robert Downey Jr., \nChris Evans, \nMark Ruffa...","/name/nm0751648/,/name/nm0000375/,/name/nm0262...",1148100.0,858373000.0
40,tt22769820,Legion of Super-Heroes,2023,PG-13,83 min,"Animation, Action, Sci-Fi",5.7,"Kara, devastated by the loss of Krypton, strug...",Jeff Wamester,/name/nm5208146/,"Jensen Ackles, \nMatt Bomer, \nDarin De Paul, ...","/name/nm0010075/,/name/nm0093589/,/name/nm0210...",1200.0,NaN
41,tt12261776,65,2023,NaN,NaN,"Action, Adventure, Drama",NaN,An astronaut crash lands on a mysterious plane...,"Scott Beck, \nBryan Woods",/name/nm1399714/,"Adam Driver, \nAriana Greenblatt, \nChloe Cole...","/name/nm1456816/,/name/nm3485845/,/name/nm7567...",NaN,NaN
42,tt13614388,Little Dixie,2023,R,105 min,"Action, Crime, Thriller",4.8,Doc facilitates a fragile truce between the Go...,John Swab,/name/nm6461537/,"Frank Grillo, \nAnnabeth Gish, \nEric Dane, \n...","/name/nm0342029/,/name/nm0001272/,/name/nm0199...",356.0,NaN
43,tt15600222,An Action Hero,2022,NaN,130 min,"Action, Comedy, Crime",7.2,Youth Icon. Superstar. Action Hero. At the age...,Anirudh Iyer,/name/nm5518137/,"Ayushmann Khurrana, \nJaideep Ahlawat, \nNeera...","/name/nm4731677/,/name/nm4188433/,/name/nm6697...",24628.0,NaN
44,tt10298840,Strange World,2022,PG,102 min,"Animation, Action, Adventure",5.6,The legendary Clades are a family of explorers...,"Don Hall, \nQui Nguyen",/name/nm2320658/,"Jake Gyllenhaal, \nJaboukie Young-White, \nGab...","/name/nm5945690/,/name/nm0350453/,/name/nm7187...",34585.0,NaN
45,tt2911666,John Wick,2014,R,101 min,"Action, Crime, Thriller",7.4,An ex-hit-man comes out of retirement to track...,"Chad Stahelski, \nDavid Leitch",/name/nm0821432/,"Keanu Reeves, \nMichael Nyqvist, \nAlfie Allen...","/name/nm0500610/,/name/nm0000206/,/name/nm0638...",644257.0,43037835.0
46,tt8367814,The Gentlemen,2019,R,113 min,"Action, Comedy, Crime",7.8,An American expat tries to sell off his highly...,Guy Ritchie,/name/nm0005363/,"Matthew McConaughey, \nCharlie Hunnam, \nMiche...","/name/nm0000190/,/name/nm0402271/,/name/nm1890...",348209.0,36471795.0
47,tt1856101,Blade Runner 2049,2017,R,164 min,"Action, Drama, Mystery",8.0,Young Blade Runner K's discovery of a long-bur...,Denis Villeneuve,/name/nm0898288/,"Harrison Ford, \nRyan Gosling, \nAna de Armas,...","/name/nm0000148/,/name/nm0331516/,/name/nm1869...",586274.0,92054159.0
48,tt5433138,F9: The Fast Saga,2021,PG-13,143 min,"Action, Crime, Thriller",5.2,Dom and the crew must take on an international...,Justin Lin,/name/nm0510912/,"Vin Diesel, \nMichelle Rodriguez, \nJordana Br...","/name/nm0004874/,/name/nm0735442/,/name/nm0108...",136715.0,173202780.0
49,tt12003946,Violent Night,2022,R,112 min,"Action, Comedy, Crime",6.7,When a group of mercenaries attack the estate ...,Tommy Wirkola,/name/nm2482088/,"David Harbour, \nJohn Leguizamo, \nBeverly D'A...","/name/nm1092086/,/name/nm0000491/,/name/nm0000...",61464.0,NaN

In [5]:
movies1.describe()

              rating         votes   gross(in $)
count  123387.000000  1.233890e+05  1.036700e+04
mean        5.866834  6.546318e+03  2.443682e+07
std         1.332837  4.867225e+04  5.514782e+07
min         1.000000  5.000000e+00  1.000000e+00
25%         5.100000  2.900000e+01  2.231720e+05
50%         6.000000  1.190000e+02  3.247524e+06
75%         6.800000  6.830000e+02  2.409090e+07
max        10.000000  2.675531e+06  9.366622e+08

In [6]:
shuffled_data = movies1.sample(frac=1, random_state=42).reset_index(drop=True)

In [7]:
movies1.shape

(213858, 14)

In [8]:

reduced_data = shuffled_data.sample(frac=0.50, random_state=42)

In [9]:
reduced_data.head

<bound method NDFrame.head of           movie_id                 movie_name  year certificate  runtime  \
109990   tt5910212            Bhalobasar Rong  2012         NaN  156 min
212506   tt6793198                 Ljusningen  2017         NaN   82 min
190802   tt0025895          Ticket to a Crime  1934    Approved   67 min
11508   tt12945592      If It Makes You Happy  2019         NaN   70 min
77785   tt14857102  The House on Gallows Hill  2021         NaN   95 min
...            ...                        ...   ...         ...      ...
160252  tt12714890        A Clockwork Macabre   NaN         NaN      NaN
213110   tt1590285     Blood of the Samurai 2  2007         NaN   69 min
141933  tt21371106             School Romance  2021         NaN      NaN
114906   tt0023367                Rackety Rax  1932      Passed   70 min
67250    tt0032590               Hi-Yo Silver  1940    Approved   69 min

                        genre  rating  \
109990        Comedy, Romance     5.5
212506              Adventure     7.6
190802  Action, Comedy, Crime     5.5
11508                 Romance     NaN
77785                  Horror     NaN
...                       ...     ...
160252       Horror, Thriller     NaN
213110                 Action     NaN
141933                Romance     NaN
114906  Action, Comedy, Crime     4.9
67250         Family, Western     6.7

                                              description  \
109990             A beautiful story of love and passion.
212506  Dante has a writer's block and expects a child...
190802  A Man is found murdered at the Lido Country Cl...
11508                                          Add a Plot
77785   A Real Estate Agent, anxious to make a sale to...
...                                                   ...
160252  A struggling doctor and his ward are called to...
213110  The sequel to the award-winning independent fi...
141933                                         Add a Plot
114906  Gambler/racketeer "Knucks" McGloin takes note ...
67250   Edited version of the 1938 Republic serial "Th...

                              director        director_id  \
109990                 Shahin, \nSumon   /name/nm5042604/
212506                     Johan Melin   /name/nm1195553/
190802                Lewis D. Collins   /name/nm0172485/
11508                              NaN                NaN
77785                     James Ahearn   /name/nm9358517/
...                                ...                ...
160252                  Dallas Burgess   /name/nm5415220/
213110                  Aaron Yamasato   /name/nm1115646/
141933                      Alfa Aryan  /name/nm13864186/
114906                Alfred L. Werker   /name/nm0921288/
67250   John English, \nWilliam Witney   /name/nm0257638/

                                                     star  \
109990  Bappy Chowdhury, \nMahiya Mahi, \nAmit Hasan, ...
212506  Nicolas Bro, \nJakob Cedergren, \nAnna Fabrici...
190802  Ralph Graves, \nLois Wilson, \nLola Lane, \nJa...
11508                                                 NaN
77785   Katrina Kusa, \nSheldon Ingram, \nKatheen Vale...
...                                                   ...
160252                                                NaN
213110  Daisuke Ban, \nLeroy Bartlett, \nShawn Forsyth...
141933      Alfa Aryan, \nYashika Rawat, \nShefali Saxena
114906  Victor McLaglen, \nGreta Nissen, \nNell O'Day,...
67250   Chief Thundercloud, \nLynne Roberts, \nStanley...

                                                  star_id  votes  gross(in $)
109990  /name/nm5042675/,/name/nm5497348/,/name/nm5496...   29.0          NaN
212506  /name/nm0110334/,/name/nm0147767/,/name/nm2409...   18.0          NaN
190802  /name/nm0336339/,/name/nm0933773/,/name/nm0485...   45.0          NaN
11508                                                 NaN    NaN          NaN
77785   /name/nm10054490/,/name/nm12665034/,/name/nm12...    NaN          NaN
...                                                   ...    ...          ...
160252                                                NaN    NaN          NaN
213110  /name/nm0051499/,/name/nm1113422/,/name/nm1113...    NaN          NaN
141933  /name/nm13864186/,/name/nm13864629/,/name/nm13...    NaN          NaN
114906  /name/nm0572142/,/name/nm0632895/,/name/nm0640...   23.0          NaN
67250   /name/nm0936823/,/name/nm0862086/,/name/nm0731...   79.0          NaN

[106929 rows x 14 columns]>

In [10]:
reduced_data.to_csv("combined_movies", index = False)

In [11]:
df = pd.read_csv('combined_movies')

In [80]:
df['movie_name'].dropna

<bound method Series.dropna of 0                   Bhalobasar Rong
1                        Ljusningen
2                 Ticket to a Crime
3             If It Makes You Happy
4         The House on Gallows Hill
                    ...
106924          A Clockwork Macabre
106925       Blood of the Samurai 2
106926               School Romance
106927                  Rackety Rax
106928                 Hi-Yo Silver
Name: movie_name, Length: 106929, dtype: object>

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

from nltk.corpus import stopwords
import nltk

In [13]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
# Initialize lemmatizer and stopwords
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))
# nltk.download('wordnet')
def preprocess_text(text):
    text = text.lower()  # Lowercasing
    text = re.sub(r'\b(\w+)\s+\1\b', r'\1', text)  # Removing repeated words
    text = re.sub(r'[^a-z\s]', '', text)  # Removing non-alphabetic characters
    words = text.split()
    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]  # Lemmatization
    return " ".join(words)

df['description'] = df['description'].apply(preprocess_text)
df['genre'] = df ['genre'].apply(preprocess_text)
print(df['description'])
print(df['genre'])

0                              beautiful story love passion
1         dante writer block expects child anette workin...
2         man found murdered lido country club although ...
3                                                  add plot
4         real estate agent anxious make sale prospectiv...
                                ...
106924    struggling doctor ward called england perform ...
106925    sequel awardwinning independent film two ordin...
106926                                             add plot
106927    gamblerracketeer knucks mcgloin take note much...
106928           edited version republic serial lone ranger
Name: description, Length: 106929, dtype: object
0              comedy romance
1                   adventure
2         action comedy crime
3                     romance
4                      horror
                 ...
106924        horror thriller
106925                 action
106926                romance
106927    action comedy crime
106928         family western
Name: genre, Length: 106929, dtype: object

In [14]:
nltk.download('stopwords')
vectorizer =CountVectorizer(stop_words=stopwords.words('english'), max_features=1000)
X = vectorizer.fit_transform(df['description'])
keywords = vectorizer.get_feature_names_out()
print('Top keywords:', keywords)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vtebo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Top keywords: ['abandoned' 'ability' 'able' 'accident' 'accidentally' 'accused' 'across'
 'act' 'action' 'activity' 'actor' 'actress' 'actually' 'adaptation' 'add'
 'adult' 'adventure' 'affair' 'africa' 'african' 'age' 'agency' 'agent'
 'ago' 'air' 'alien' 'alive' 'almost' 'alone' 'along' 'also' 'always'
 'america' 'american' 'among' 'ancient' 'angel' 'angeles' 'animal'
 'another' 'answer' 'anthology' 'anything' 'apart' 'apartment' 'appears'
 'area' 'army' 'around' 'arrives' 'art' 'artist' 'asks' 'aspiring'
 'assassin' 'assigned' 'attack' 'attempt' 'author' 'avenge' 'away' 'baby'
 'back' 'bad' 'band' 'bandit' 'bank' 'bar' 'based' 'battle' 'beach' 'bear'
 'beautiful' 'beauty' 'became' 'become' 'becomes' 'becoming' 'begin'
 'beginning' 'behind' 'belief' 'believe' 'beloved' 'best' 'better'
 'beyond' 'big' 'biggest' 'birth' 'bizarre' 'black' 'blind' 'blood' 'body'
 'bond' 'book' 'border' 'born' 'bos' 'boy' 'boyfriend' 'break' 'bring'
 'brings' 'british' 'broken' 'brother' 'brought' 'brutal' 'build'
 'building' 'business' 'businessman' 'cabin' 'california' 'call' 'called'
 'came' 'camp' 'cannot' 'cant' 'captain' 'capture' 'captured' 'car' 'care'
 'career' 'case' 'cast' 'cat' 'catch' 'caught' 'cause' 'center' 'century'
 'challenge' 'champion' 'chance' 'change' 'chaos' 'character' 'chief'
 'child' 'childhood' 'china' 'chinese' 'choice' 'christmas' 'cia'
 'circumstance' 'city' 'civil' 'claim' 'class' 'classic' 'close' 'club'
 'college' 'come' 'comedy' 'comic' 'coming' 'commit' 'committed'
 'community' 'company' 'competition' 'con' 'conflict' 'confront'
 'consequence' 'conspiracy' 'control' 'cop' 'corrupt' 'corruption' 'could'
 'country' 'countryside' 'couple' 'course' 'cousin' 'crash' 'create'
 'created' 'creature' 'crew' 'crime' 'criminal' 'crisis' 'cross' 'cult'
 'curse' 'dad' 'dance' 'dancer' 'danger' 'dangerous' 'dark' 'date'
 'daughter' 'david' 'day' 'de' 'dead' 'deadly' 'deal' 'dealer' 'death'
 'debt' 'decide' 'decides' 'decision' 'deep' 'defeat' 'demon' 'desert'
 'desire' 'desperate' 'despite' 'destiny' 'destroy' 'detective'
 'determined' 'devil' 'diamond' 'die' 'died' 'different' 'directed'
 'director' 'disappearance' 'disappears' 'discover' 'discovered'
 'discovers' 'discovery' 'doctor' 'documentary' 'doesnt' 'dog' 'dont'
 'door' 'dr' 'dragon' 'drama' 'dream' 'drive' 'driver' 'drug' 'due' 'dy'
 'dying' 'early' 'earth' 'east' 'eccentric' 'effort' 'el' 'elite' 'embark'
 'embarks' 'empire' 'employee' 'encounter' 'end' 'enemy' 'england'
 'english' 'enough' 'enter' 'enters' 'entire' 'epic' 'escape' 'estate'
 'estranged' 'europe' 'eve' 'even' 'event' 'eventually' 'ever' 'every'
 'everyone' 'everything' 'evil' 'existence' 'experience' 'experiment'
 'eye' 'face' 'fact' 'factory' 'faith' 'fall' 'falling' 'family' 'famous'
 'fan' 'fantasy' 'far' 'farm' 'farmer' 'fate' 'father' 'fbi' 'fear'
 'feature' 'feel' 'feeling' 'fellow' 'female' 'fiance' 'fight' 'fighter'
 'fighting' 'figure' 'film' 'filmmaker' 'final' 'finally' 'find' 'finding'
 'fire' 'first' 'five' 'follow' 'following' 'follows' 'football' 'force'
 'forced' 'forest' 'forever' 'form' 'former' 'fortune' 'found' 'four'
 'france' 'free' 'freedom' 'french' 'friend' 'friendship' 'front' 'full'
 'fun' 'future' 'gain' 'game' 'gang' 'gangster' 'gay' 'general' 'george'
 'german' 'germany' 'get' 'getting' 'ghost' 'giant' 'girl' 'girlfriend'
 'give' 'given' 'go' 'god' 'going' 'gold' 'gone' 'good' 'got' 'government'
 'grandfather' 'great' 'greatest' 'group' 'guard' 'gun' 'guy' 'hand'
 'handsome' 'happen' 'happened' 'happens' 'happy' 'hard' 'haunted' 'head'
 'heart' 'heist' 'held' 'hell' 'help' 'hero' 'hidden' 'hide' 'hiding'
 'high' 'hire' 'hired' 'history' 'hit' 'hitman' 'hold' 'holiday'
 'hollywood' 'home' 'hometown' 'hong' 'hope' 'horror' 'horse' 'hospital'
 'hostage' 'hotel' 'hour' 'house' 'however' 'human' 'humanity' 'hunt'
 'hunted' 'hunter' 'hunting' 'husband' 'idea' 'identity' 'ii' 'illegal'
 'important' 'incident' 'including' 'india' 'indian' 'innocent' 'inside'
 'inspector' 'inspired' 'instead' 'intelligence' 'international'
 'invasion' 'investigate' 'investigates' 'investigating' 'investigation'
 'investigator' 'involved' 'involving' 'island' 'isolated' 'issue'
 'italian' 'italy' 'jack' 'jail' 'james' 'japan' 'japanese' 'job' 'joe'
 'john' 'join' 'journalist' 'journey' 'jungle' 'justice' 'keep' 'kept'
 'kid' 'kidnap' 'kidnapped' 'kill' 'killed' 'killer' 'killing' 'kind'
 'king' 'kingdom' 'know' 'known' 'kong' 'korean' 'la' 'lady' 'lake' 'land'
 'large' 'last' 'late' 'later' 'law' 'lawyer' 'lead' 'leader' 'leading'
 'leaf' 'learn' 'learns' 'leave' 'leaving' 'led' 'left' 'legend'
 'legendary' 'let' 'letter' 'lie' 'life' 'lifestyle' 'light' 'like' 'line'
 'little' 'live' 'living' 'local' 'london' 'lonely' 'long' 'look'
 'looking' 'lord' 'los' 'loses' 'losing' 'loss' 'lost' 'lot' 'love'
 'loved' 'lover' 'machine' 'made' 'mafia' 'magic' 'magical' 'main' 'major'
 'make' 'making' 'male' 'man' 'manager' 'mansion' 'many' 'marriage'
 'married' 'marries' 'marry' 'martial' 'mary' 'master' 'matter' 'may'
 'mean' 'meanwhile' 'medical' 'medium' 'meet' 'meeting' 'member' 'memory'
 'men' 'mental' 'met' 'mexican' 'mexico' 'michael' 'middle' 'might'
 'military' 'million' 'mind' 'missing' 'mission' 'mob' 'model' 'modern'
 'mom' 'moment' 'money' 'monster' 'month' 'mother' 'mountain' 'move'
 'movie' 'mr' 'much' 'murder' 'murdered' 'murderer' 'music' 'musical'
 'musician' 'must' 'mysterious' 'mysteriously' 'mystery' 'name' 'named'
 'national' 'native' 'nature' 'nazi' 'near' 'need' 'neighbor'
 'neighborhood' 'never' 'new' 'newly' 'news' 'next' 'night' 'nightmare'
 'north' 'nothing' 'notorious' 'novel' 'number' 'nurse' 'obsessed' 'offer'
 'office' 'officer' 'old' 'older' 'one' 'open' 'operation' 'order'
 'ordinary' 'organization' 'original' 'orphan' 'others' 'outside' 'owner'
 'pair' 'paranormal' 'parent' 'paris' 'park' 'part' 'partner' 'party'
 'passion' 'past' 'path' 'patient' 'paul' 'pay' 'peace' 'people' 'perfect'
 'person' 'personal' 'peter' 'photographer' 'pilot' 'pirate' 'place'
 'plan' 'plane' 'planet' 'play' 'player' 'plot' 'point' 'police'
 'policeman' 'political' 'politician' 'poor' 'popular' 'power' 'powerful'
 'pregnant' 'present' 'president' 'priest' 'prince' 'princess' 'prison'
 'prisoner' 'private' 'problem' 'professional' 'professor' 'project'
 'prostitute' 'protect' 'prove' 'psychological' 'put' 'queen' 'quest'
 'question' 'quickly' 'race' 'radio' 'raised' 'reach' 'real' 'reality'
 'realize' 'realizes' 'really' 'reason' 'rebel' 'receives' 'recently'
 'red' 'refuse' 'relationship' 'released' 'remote' 'reporter' 'rescue'
 'research' 'resident' 'responsible' 'result' 'retired' 'return' 'revenge'
 'revolves' 'rich' 'ride' 'right' 'ring' 'rise' 'risk' 'rival' 'road'
 'rob' 'robber' 'robbery' 'robert' 'robot' 'rock' 'role' 'romance'
 'romantic' 'room' 'rule' 'run' 'running' 'rural' 'russian' 'ruthless'
 'sam' 'san' 'save' 'scene' 'school' 'scientist' 'sea' 'search'
 'searching' 'second' 'secret' 'security' 'see' 'seek' 'seeking'
 'seemingly' 'seems' 'seen' 'sell' 'sends' 'sent' 'separated' 'sequel'
 'serial' 'series' 'service' 'set' 'seven' 'several' 'sex' 'sexual'
 'share' 'sheriff' 'shes' 'ship' 'short' 'shot' 'show' 'side' 'simple'
 'since' 'singer' 'single' 'sinister' 'sister' 'situation' 'six' 'skill'
 'small' 'social' 'society' 'soldier' 'solve' 'someone' 'something' 'son'
 'song' 'soon' 'soul' 'south' 'soviet' 'space' 'spanish' 'special' 'spend'
 'spirit' 'sport' 'spy' 'st' 'stage' 'stand' 'star' 'start' 'state'
 'station' 'stay' 'steal' 'step' 'still' 'stolen' 'stop' 'store' 'story'
 'stranded' 'strange' 'stranger' 'street' 'strike' 'struggle' 'struggling'
 'student' 'study' 'stumble' 'success' 'successful' 'suddenly' 'suffering'
 'suicide' 'summary' 'summer' 'super' 'supernatural' 'survival' 'survive'
 'survivor' 'suspect' 'synopsis' 'system' 'take' 'taken' 'taking' 'tale'
 'target' 'task' 'teacher' 'team' 'teen' 'teenage' 'teenager' 'tell' 'ten'
 'terrifying' 'terror' 'terrorist' 'test' 'texas' 'th' 'theyre' 'thief'
 'thing' 'think' 'though' 'thought' 'threat' 'threatens' 'three'
 'thriller' 'time' 'together' 'told' 'tom' 'took' 'top' 'tough' 'town'
 'track' 'tragedy' 'tragic' 'train' 'trapped' 'travel' 'traveling'
 'treasure' 'trial' 'trip' 'trouble' 'troubled' 'true' 'truth' 'try'
 'trying' 'turn' 'turned' 'tv' 'twin' 'two' 'ultimate' 'unable' 'uncle'
 'uncover' 'undercover' 'underground' 'underworld' 'unexpected' 'unit'
 'united' 'universe' 'university' 'unknown' 'unlikely' 'upon' 'us' 'use'
 'used' 'using' 'vacation' 'vampire' 'various' 'vengeance' 'veteran'
 'victim' 'video' 'village' 'violence' 'violent' 'vision' 'visit' 'wake'
 'want' 'wanted' 'war' 'warrior' 'watch' 'water' 'way' 'wealthy' 'weapon'
 'wedding' 'week' 'weekend' 'well' 'went' 'west' 'white' 'whole' 'whose'
 'widow' 'wife' 'wild' 'win' 'wish' 'witch' 'within' 'without' 'witness'
 'woman' 'wood' 'work' 'worker' 'working' 'world' 'would' 'wrap' 'writer'
 'wrong' 'year' 'yearold' 'yet' 'york' 'young' 'younger' 'youth' 'zombie']

In [15]:
nltk.download('stopwords')
vectorizer =CountVectorizer(stop_words=stopwords.words('english'), max_features=1000)
X1 = vectorizer.fit_transform(df['genre'])
keywords = vectorizer.get_feature_names_out()
print('Top keywords:', keywords)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vtebo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Top keywords: ['action' 'adult' 'adventure' 'animation' 'biography' 'comedy' 'crime'
 'drama' 'family' 'fantasy' 'filmnoir' 'gameshow' 'history' 'horror'
 'music' 'musical' 'mystery' 'news' 'realitytv' 'romance' 'scifi' 'sport'
 'talkshow' 'thriller' 'war' 'western']

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TF-IDF Vectorizer
vectorizer = TfidfVectorizer(max_features=500)

# Convert cleaned reviews into a TF-IDF matrix
X = vectorizer.fit_transform(df['description'])

tfidf_keywords = vectorizer.get_feature_names_out()
print('TF-IDF Keywords:', tfidf_keywords)

TF-IDF Keywords: ['abandoned' 'accident' 'accidentally' 'across' 'action' 'actor' 'actress'
 'add' 'adventure' 'affair' 'age' 'agent' 'ago' 'alien' 'alone' 'along'
 'also' 'always' 'america' 'american' 'ancient' 'another' 'apartment'
 'army' 'around' 'arrives' 'art' 'artist' 'attack' 'attempt' 'away' 'baby'
 'back' 'bad' 'band' 'bank' 'based' 'battle' 'beautiful' 'become'
 'becomes' 'begin' 'behind' 'belief' 'best' 'big' 'black' 'blood' 'body'
 'book' 'bos' 'boy' 'boyfriend' 'break' 'bring' 'british' 'brother'
 'business' 'call' 'called' 'camp' 'captain' 'car' 'care' 'career' 'case'
 'caught' 'cause' 'century' 'chance' 'change' 'character' 'child'
 'childhood' 'china' 'chinese' 'christmas' 'city' 'college' 'come'
 'comedy' 'community' 'company' 'control' 'cop' 'corrupt' 'could'
 'country' 'couple' 'creature' 'crew' 'crime' 'criminal' 'dangerous'
 'dark' 'daughter' 'day' 'de' 'dead' 'deadly' 'deal' 'death' 'decide'
 'decides' 'deep' 'demon' 'desperate' 'detective' 'different' 'director'
 'discover' 'discovers' 'doctor' 'doesnt' 'dog' 'dr' 'drama' 'dream'
 'driver' 'drug' 'due' 'dy' 'early' 'earth' 'encounter' 'end' 'enemy'
 'escape' 'even' 'event' 'ever' 'every' 'everyone' 'everything' 'evil'
 'experience' 'eye' 'face' 'fall' 'family' 'famous' 'fate' 'father' 'fear'
 'feature' 'female' 'fight' 'fighting' 'film' 'find' 'first' 'five'
 'follow' 'following' 'follows' 'force' 'forced' 'forest' 'form' 'former'
 'found' 'four' 'french' 'friend' 'friendship' 'full' 'future' 'game'
 'gang' 'gangster' 'german' 'get' 'getting' 'ghost' 'girl' 'girlfriend'
 'give' 'go' 'god' 'going' 'gold' 'good' 'government' 'great' 'group'
 'guy' 'hand' 'haunted' 'he' 'head' 'heart' 'hell' 'help' 'hero' 'hidden'
 'high' 'hired' 'history' 'hit' 'home' 'hope' 'horror' 'hotel' 'house'
 'however' 'human' 'hunt' 'hunter' 'husband' 'identity' 'ii' 'india'
 'indian' 'inside' 'international' 'investigate' 'investigation'
 'involved' 'island' 'japanese' 'job' 'john' 'join' 'journalist' 'journey'
 'keep' 'kid' 'kidnapped' 'kill' 'killed' 'killer' 'killing' 'king' 'know'
 'known' 'la' 'lady' 'land' 'last' 'late' 'later' 'law' 'lead' 'leader'
 'leaf' 'learn' 'learns' 'leave' 'left' 'legend' 'legendary' 'life' 'like'
 'little' 'live' 'living' 'local' 'london' 'long' 'look' 'looking' 'los'
 'loses' 'lost' 'love' 'lover' 'made' 'make' 'making' 'man' 'many'
 'marriage' 'married' 'marry' 'martial' 'master' 'may' 'meet' 'member'
 'memory' 'men' 'middle' 'military' 'mind' 'missing' 'mission' 'modern'
 'money' 'monster' 'mother' 'mountain' 'move' 'movie' 'much' 'murder'
 'murdered' 'music' 'must' 'mysterious' 'mystery' 'name' 'named' 'near'
 'need' 'never' 'new' 'next' 'night' 'nightmare' 'nothing' 'novel'
 'officer' 'old' 'one' 'order' 'owner' 'parent' 'part' 'partner' 'party'
 'past' 'path' 'people' 'person' 'personal' 'place' 'plan' 'planet' 'play'
 'plot' 'police' 'political' 'poor' 'power' 'powerful' 'prince' 'prison'
 'private' 'problem' 'professional' 'professor' 'protect' 'put' 'quest'
 'race' 'real' 'reality' 'relationship' 'remote' 'reporter' 'rescue'
 'return' 'revenge' 'rich' 'right' 'rival' 'road' 'romance' 'romantic'
 'run' 'russian' 'save' 'school' 'scientist' 'sea' 'search' 'second'
 'secret' 'see' 'seek' 'seems' 'sent' 'serial' 'series' 'set' 'several'
 'sex' 'shes' 'ship' 'short' 'show' 'side' 'since' 'singer' 'single'
 'sister' 'six' 'small' 'social' 'society' 'soldier' 'solve' 'someone'
 'something' 'son' 'soon' 'soul' 'south' 'space' 'special' 'spirit' 'spy'
 'star' 'start' 'state' 'stay' 'steal' 'still' 'stolen' 'stop' 'story'
 'strange' 'stranger' 'street' 'struggle' 'struggling' 'student'
 'successful' 'suddenly' 'suicide' 'summary' 'summer' 'supernatural'
 'survive' 'suspect' 'take' 'taken' 'taking' 'tale' 'teacher' 'team'
 'teen' 'teenage' 'teenager' 'tell' 'terrorist' 'th' 'thief' 'thing'
 'think' 'three' 'thriller' 'time' 'together' 'town' 'track' 'train'
 'trapped' 'travel' 'treasure' 'trip' 'trouble' 'troubled' 'true' 'truth'
 'try' 'trying' 'turn' 'turned' 'two' 'uncle' 'unexpected' 'unknown'
 'upon' 'us' 'use' 'vacation' 'vampire' 'victim' 'video' 'village'
 'violent' 'visit' 'want' 'war' 'way' 'wealthy' 'wedding' 'weekend' 'well'
 'white' 'whose' 'wife' 'win' 'within' 'without' 'witness' 'woman' 'wood'
 'work' 'working' 'world' 'would' 'writer' 'wrong' 'year' 'yearold' 'york'
 'young' 'zombie']

In [17]:
from scipy.sparse import hstack
X_combined = hstack([X, X1])

In [60]:
from sklearn.cluster import KMeans
import numpy as np


# Apply KMeans clustering
num_clusters = 6  # Assume 3 clusters for positive, negative, and neutral
kmeans = KMeans(n_clusters=num_clusters, random_state=42)
kmeans.fit(X_combined)

# Assign cluster labels to reviews
df['sentiment_cluster'] = kmeans.labels_

# print(df[['description', 'sentiment_cluster']])

C:\Users\vtebo\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

In [61]:
print(df[['genre','description', 'sentiment_cluster']])

                      genre  \
0            comedy romance
1                 adventure
2       action comedy crime
3                   romance
4                    horror
...                     ...
106924      horror thriller
106925               action
106926              romance
106927  action comedy crime
106928       family western

                                              description  sentiment_cluster
0                            beautiful story love passion                  4
1       dante writer block expects child anette workin...                  0
2       man found murdered lido country club although ...                  1
3                                                add plot                  4
4       real estate agent anxious make sale prospectiv...                  5
...                                                   ...                ...
106924  struggling doctor ward called england perform ...                  5
106925  sequel awardwinning independent film two ordin...                  1
106926                                           add plot                  4
106927  gamblerracketeer knucks mcgloin take note much...                  1
106928         edited version republic serial lone ranger                  0

[106929 rows x 3 columns]

In [62]:
df['sentiment_cluster'].unique()

array([4, 0, 1, 5, 2, 3])

In [64]:
import numpy as np
df[df['sentiment_cluster'] == 5]['genre'].unique()

array(['horror', 'horror scifi thriller', 'fantasy horror musical',
       'drama horror', 'horror mystery thriller', 'horror scifi',
       'horror romance thriller', 'comedy horror', 'horror mystery',
       'action horror thriller', 'drama horror mystery',
       'drama horror thriller', 'horror thriller',
       'mystery thriller horror', 'animation drama horror',
       'action comedy horror', 'crime horror thriller',
       'horror mystery scifi', 'adventure fantasy horror',
       'fantasy horror', 'comedy drama horror', 'action horror mystery',
       'action fantasy horror', 'fantasy horror mystery',
       'drama fantasy horror', 'comedy horror mystery',
       'comedy fantasy horror', 'fantasy horror thriller',
       'action horror scifi', 'crime horror', 'horror comedy',
       'history horror thriller', 'comedy horror musical',
       'fantasy horror scifi', 'drama horror scifi', 'horror romance',
       'horror western', 'action horror', 'animation horror',
       'adventure comedy horror', 'comedy horror scifi',
       'comedy adventure horror', 'comedy horror thriller',
       'action crime horror', 'fantasy horror romance',
       'adventure horror', 'crime horror mystery',
       'horror musical thriller', 'adventure horror thriller',
       'adventure drama horror', 'animation horror mystery',
       'comedy family horror', 'adventure horror mystery',
       'horror musical mystery', 'comedy crime horror', 'history horror',
       'adventure horror scifi', 'biography drama horror', 'horror music',
       'action horror war', 'horror comedy fantasy',
       'animation comedy horror', 'horror comedy mystery',
       'horror realitytv talkshow', 'horror romance scifi',
       'action horror western', 'horror thriller mystery',
       'drama horror music', 'comedy horror music',
       'comedy thriller horror', 'family fantasy horror',
       'horror mystery romance', 'horror fantasy', 'horror war',
       'horror thriller war', 'horror music mystery',
       'drama history horror', 'animation horror scifi',
       'action horror romance', 'horror thriller western',
       'horror music thriller', 'drama horror western',
       'crime horror romance', 'adventure family horror',
       'horror musical', 'horror realitytv', 'crime horror scifi',
       'drama horror war', 'thriller horror', 'crime fantasy horror',
       'crime horror action', 'horror realitytv thriller',
       'fantasy horror music', 'animation action horror',
       'history horror musical', 'horror mystery action',
       'crime horror musical', 'horror comedy music',
       'drama family horror', 'filmnoir horror', 'scifi horror',
       'drama horror musical', 'family horror scifi',
       'filmnoir horror thriller', 'action scifi horror',
       'horror mystery western', 'adventure history horror',
       'horror scifi war', 'scifi action horror', 'crime history horror',
       'adventure crime horror', 'adventure horror fantasy',
       'family horror mystery', 'action family horror',
       'comedy history horror', 'crime thriller horror', 'family horror',
       'horror action scifi', 'thriller horror mystery',
       'biography horror thriller', 'musical drama horror',
       'horror mystery drama', 'crime horror music',
       'adventure horror romance', 'biography comedy horror',
       'comedy horror crime', 'horror drama', 'horror music scifi',
       'mystery western horror', 'fantasy horror western',
       'animation horror thriller', 'animation fantasy horror',
       'biography horror', 'horror crime', 'drama thriller horror',
       'filmnoir horror mystery', 'biography fantasy horror',
       'fantasy horror war', 'comedy scifi horror',
       'action thriller horror', 'biography crime horror',
       'history horror war', 'horror action', 'history horror mystery',
       'mystery horror', 'fantasy horror comedy',
       'horror western thriller', 'musical horror',
       'horror musical scifi', 'comedy horror western',
       'comedy horror sport', 'animation horror romance',
       'drama mystery horror', 'family horror thriller',
       'action horror music', 'horror drama mystery',
       'mystery fantasy horror', 'horror thriller fantasy',
       'horror drama thriller', 'romance horror',
       'adventure horror western', 'drama horror fantasy',
       'scifi comedy horror', 'comedy horror war',
       'action history horror', 'horror sport', 'action horror sport',
       'animation horror war', 'animation adventure horror',
       'western horror', 'scifi horror thriller', 'thriller crime horror',
       'animation horror music', 'horror thriller action'], dtype=object)

In [127]:
# Custom function to convert Roman numerals to integers
def roman_to_int(roman):
    roman_dict = {
        'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000
    }
    result = 0
    prev_value = 0
    for char in reversed(roman):
        value = roman_dict[char]
        if value < prev_value:
            result -= value
        else:
            result += value
        prev_value = value
    return result
# Convert Roman numerals to integers using apply and the custom function
# Function to handle conversion with try-except
def convert_year(value):
    try:
        # Try converting to integer directly
        return int(value)
    except ValueError:
        # If it fails, try converting Roman numeral to integer
        return roman_to_int(value)

# Apply the conversion function to the 'year' column
df['year'] = df['year'].apply(convert_year)

In [123]:
# fill null values in the rating column with the mean of the column
df['rating'] = df['rating'].fillna(np.mean(df['rating']))

In [124]:
# Convert 'year' column to integersy
df['year'].dtype

dtype('int64')

In [126]:
# recommendation is performed by comparing the user's mood with the label of the movies then the movies are recommended first of all based on ratings, then year.
def recommend_movies_based_on_user_mood(user_mood, movies, top_n=5):
    # Filter movies based on the user's mood
    if user_mood == 'positive':
        recommended_movies = movies[movies['sentiment_cluster'] == 3]
    elif user_mood == 'negative':
        recommended_movies = movies[movies['sentiment_cluster'] == 2]
    else:  # neutral mood
        recommended_movies = movies[movies['sentiment_cluster'] == 1]
    
    # Sort the filtered movies by 'rating' (highest first) and then by 'year' (latest first)
    recommended_movies_sorted = recommended_movies.sort_values(by=['rating', 'year'], ascending=[False, False])
    
    # Get the top N movies based on the user's mood, highest rating, and latest year
    return recommended_movies_sorted[['movie_name', 'sentiment_cluster', 'year', 'rating']].head(top_n)

# Recommend movies based on user's mood
recommended_movies = recommend_movies_based_on_user_mood("positve", df, 5)
print("Recommended Movies based on your mood:")
print(recommended_movies)

Recommended Movies based on your mood:
                                            movie_name  sentiment_cluster  \
42388         An Example of Teenage Boredom: The Movie                  1
97979                                         Low Heat                  1
99307                                  The Key of Baku                  1
43878  The Shoonyah: Chapter 1 - Blow of the War Horns                  1
78053                                           Masand                  1

       year  rating
42388  2022    10.0
97979  2021     9.9
99307  2022     9.8
43878  2021     9.8
78053  2022     9.7

Index(['movie_id', 'movie_name', 'year', 'certificate', 'runtime', 'genre',
       'rating', 'description', 'director', 'director_id', 'star', 'star_id',
       'votes', 'gross(in $)', 'sentiment_cluster'],
      dtype='object')

MemoryError: Unable to allocate 85.2 GiB for an array with shape (106929, 106929) and data type float64